# Generated by Django 6.0.7 on 2026-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle', models.CharField(choices=[('Taxi', 'Taxi'), ('SUV', 'SUV'), ('Tempo Traveller', 'Tempo Traveller'), ('Mini Bus', 'Mini Bus'), ('Bus', 'Bus')], max_length=50)),
                ('pickup', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('members', models.PositiveIntegerField(default=1)),
                ('trip_details', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Enquiry',
                'verbose_name_plural': 'Travel Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
