# Generated by Django 6.0.7 on 2026-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Ertiga', 'Ertiga'), ('Innova Crysta', 'Innova Crysta'), ('Tempo Traveller AC', 'Tempo Traveller AC'), ('Tempo Traveller Non AC', 'Tempo Traveller Non AC'), ('Traveller Coach 20', 'Traveller Coach 20'), ('Traveller Coach 26', 'Traveller Coach 26'), ('Mini Bus', 'Mini Bus'), ('Coach Bus', 'Coach Bus'), ('Luxury Bus', 'Luxury Bus')], max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
